window.addEventListener('DOMContentLoaded', () => {

    const i18n = {
        "Profiles": "窗口列表",
        "Proxies": "代理管理",
        "Cloud Phone": "云手机",
        "Extensions": "扩展插件",
        "Accounts": "账号管理",
        "Billing": "费用中心",
        "Settings": "设置",
        "Get 20 Profiles": "获取更多窗口",
        "Contact us": "联系我们",
        "All": "全部",
        "Official": "官方",
        "Personal": "个人",
        "Owner": "所有者",
        "Members": "成员",
        "Free": "免费版",
        "Search proxy...": "搜索代理...",
        "Add Proxy": "添加代理",
        "IP Checker": "IP 检测",
        "Source": "来源",
        "No proxies yet. Click the button below to add one.": "暂无代理。请点击下方按钮添加。",
        "Create Profile": "新建窗口",
        "Search folder": "搜索文件夹",
        "Search name or note...": "搜索名称或备注...",
        "All Profiles": "所有窗口",
        "Starred": "收藏夹",
        "Running": "运行中",
        "Trash Bin": "回收站",
        "Upgrade": "升级套餐",
        "You haven't created any profiles yet": "您尚未创建任何窗口",
        "Create a profile": "立即创建",
        "Folder": "文件夹",
        "Proxy": "代理",
        "Name": "名称",
        "Status": "状态",
        "Check Proxy": "检查代理",
        "Import": "导入",
        "Export": "导出",
        "Profile": "窗口",
        "Note": "备注",
        "Created": "创建时间",
        "FOLDERS": "文件夹",
        "Go to Profiles": "转到窗口列表",
        "Total:": "总计:",
        "Rows per page:": "每页行数:",
        "Page:": "页码:",
        "Coming Soon": "即将推出",
        "We are currently working hard on this page!": "我们目前正在努力更新此界面！",
        "Cancel": "取消",
        "Confirm": "确认",
        "Save": "保存",
        "Delete": "删除",
        "Edit": "编辑",
        "Browser": "浏览器",
        "Notes": "备注",
        "Create workspace": "创建工作区",
        "Workspace settings": "工作区设置",
        "People": "成员",
        "Invite Members": "邀请成员",
        "Invite members": "邀请成员",
        "User": "用户",
        "Role": "角色",
        "Invited by": "邀请人",
        "Joined": "加入时间",
        "Active": "活跃",
        "Invite by email": "通过邮箱邀请",
        "Invite by link": "通过链接邀请",
        "Email address": "邮箱地址",
        "Send Invite": "发送邀请",
        "Admin": "管理员",
        "Full access to workspace resources. Can manage members, settings and billing.": "拥有工作区资源的完全访问权限。可以管理成员、设置和账单。",
        "Editor": "编辑者",
        "Can create, edit and manage resources, but cannot manage members or permissions.": "可以创建、编辑和管理资源，但无法管理成员或权限。",
        "Operator": "操作员",
        "Can use shared resources, but cannot modify them.": "可以使用共享资源，但无法修改它们。",
        "Viewer": "观察者",
        "View-only access. Cannot use, edit, or manage any resource.": "仅查看权限。无法使用、编辑或管理任何资源。",
        "Refresh folders": "刷新文件夹",
        "Create Folder": "新建文件夹",
        "Folder name": "文件夹名称",
        "Create new folder": "新建文件夹",
        "Tips:": "提示:",
        "Valid :": "有效 :",
        "Duplicate :": "重复 :",
        "Invalid :": "无效 :",
        "Check All": "检查全部",
        "Username": "用户名",
        "Password": "密码",
        "Change IP URL": "更换 IP 链接",
        "Add Proxies": "添加代理",
        "You haven't added any proxies.": "您尚未添加任何代理。",
        "Refreshed successfully": "刷新成功",
        "Current Plan": "当前套餐",
        "Not upgraded": "未升级",
        "Plan": "套餐",
        "Price": "价格",
        "Renewal Date": "续费日期",
        "Users": "用户数",
        "/mo": "/月",
        "Exclusive": "尊享版",
        "Account": "账号",
        "Theme": "主题",
        "Logout": "退出登录",
        "System": "系统",
        "Light": "亮色模式",
        "Dark": "暗黑模式",
        "Create wo...": "创建工作区",
        "[Founder User] Lifetime benefit · 50 permanent free Profiles": "[创始人用户] 终身权益 · 50 个永久免费窗口",
        "[Exclusive User] Lifetime benefit · 20 permanent free Profiles": "[尊享用户] 终身权益 · 20 个永久免费窗口",
        "[Beta User] Lifetime benefit · 10 permanent free Profiles": "[内测用户] 终身权益 · 10 个永久免费窗口",
        "socks5://host:port:username:password[Change IP URL]{Note}": "socks5://主机:端口:用户名:密码[更换IP链接]{备注}",
        "http://[host-IPv6]:port:username:password[Change IP URL]{Note}": "http://[IPv6主机]:端口:用户名:密码[更换IP链接]{备注}",
        "https://username:password@host:port[Change IP URL]{Note}": "https://用户名:密码@主机:端口[更换IP链接]{备注}",
        "Restore All": "恢复全部",
        "Profile that have been in the Bin for more than 30 days will be deleted automatically.": "回收站中的窗口保留超过 30 天将被自动删除。",
        "Empty Bin Now": "立即清空",
        "No folder": "无文件夹",
        "No proxy": "无代理",
        "Deleted By": "删除者",
        "Deleted At": "删除时间",
        "Restore": "恢复",
        "Permanently delete": "永久删除",
        "Avatar": "头像",
        "Your avatar helps others recognize you across the workspace.": "您的头像有助于他人在工作区中识别您。",
        "Change": "更换",
        "Remove": "移除",
        "Nickname": "昵称",
        "Your nickname as you'd like it to be displayed on FlashID.": "您希望在 FlashID 中显示的昵称。",
        "Email": "邮箱",
        "Your email can be used to log in and to identify you.": "您的邮箱可用于登录和身份识别。",
        "Remove avatar": "移除头像",
        "Are you sure you want to delete this image?": "您确定要删除此图片吗？",
        "The first letter of your nickname will be used as the default avatar.": "您昵称的首字母将被用作默认头像。",
        "Join our Telegram group": "加入我们的 Telegram 群组",
        "Get a redeem code for 20 free profiles after joining!": "加入后获取 20 个免费窗口兑换码！",
        "Scan to join on Telegram": "扫码加入 Telegram",
        "Join via Link": "通过链接加入",
        "Profile name": "窗口名",
        "User Agent": "用户代理 (User Agent)",
        "Paste your cookies or drag and drop your file": "粘贴 Cookies 或拖放文件",
        "Allowed file types: .txt, .json; Max size of": "支持格式：.txt, .json; 最大",
        "Timezone": "时区",
        "Geolocation": "地理位置",
        "Language": "语言",
        "WebGL Info": "WebGL 信息",
        "Hardware Noise": "硬件噪音",
        "Screen": "屏幕分辨率",
        "Fonts": "字体",
        "System Fonts": "系统字体",
        "CPU": "处理器 (CPU)",
        "RAM": "内存 (RAM)",
        "Media Devices": "媒体设备",
        "Device Name": "设备名称",
        "MAC Address": "MAC 地址",
        "Do not track": "防追踪",
        "Permanently Delete": "永久删除",
        "Are you sure you want to permanently delete the selected profiles?": "您确定要永久删除选中的窗口吗？",
        "This action cannot be undone.": "此操作无法撤销。",
        "Search members... ": "搜索成员... ",
        "Add proxy": "添加代理",
        "Saved proxy": "已保存代理",
        "Upload Cookies": "上传 Cookies",
        "Off": "关闭",
        "Real": "真实",
        "Auto": "自动",
        "Manual": "手动",
        "Show more setting": "显示更多设置",
        "Hide": "隐藏",
        "Formats: JSON, Netscape": "格式: JSON, Netscape",
        "Type": "类型",
        "Host:Port": "主机:端口",
        "Host (Smart Parse is supported) : Port": "主机 (支持智能解析) : 端口",
        "Optional": "选填",
        "Change IP URL for mobile proxy": "移动代理更换 IP 链接",
        "Check": "检测",
        "Proxy has not been checked yet": "代理尚未检测",
        "Select saved proxy": "选择已保存的代理",
        "Support of the formats:\nsocks5://host:port:username:password[Change IP URL]{Note}\nhttp://[host-IPv6]:port:username:password[Change IP URL]{Note}\nhttps://username:password@host:port[Change IP URL]{Note}": "支持的格式:\nsocks5://主机:端口:用户名:密码[更换IP链接]{备注}\nhttp://[IPv6主机]:端口:用户名:密码[更换IP链接]{备注}\nhttps://用户名:密码@主机:端口[更换IP链接]{备注}",
        "Select timezone": "选择时区",
        "Latitude": "纬度",
        "Longitude": "经度",
        "Accuracy (m)": "精度 (m)",
        "Select language": "选择语言",
        "Select resolution": "选择分辨率",
        "SUMMARY": "摘要",
        "Canvas": "Canvas 画布指纹",
        "AudioContext": "AudioContext 音频指纹",
        "ClientRects": "ClientRects 元素位置指纹",
        "SpeechVoices": "SpeechVoices 语音合成指纹",
        "1. If the proxy type is not filled in, it will be added according to the set type;": "1. 如果未填写代理类型，将根据设置的类型添加；",
        "2. The proxy type only supports HTTP, HTTPS, Socks5;": "2. 代理类型仅支持 HTTP, HTTPS, Socks5；",
        "3. One proxy per line, up to 500 can be added at a time;": "3. 每行一个代理，一次最多添加 500 个；",
        "4. Supports IPv4 and IPv6, and the IPv6 host must be filled in [ ];": "4. 支持 IPv4 和 IPv6，IPv6 主机必须填写在 [ ] 中；",
        "This invitation will expire in 7 days.": "此邀请将在 7 天后过期。",
        "Workspace:": "工作区:",
        "Proxy added or imported by the user, managed independently.": "用户添加或导入的代理，独立管理。",
        "Proxy provided or purchased from FlashID, managed by the system.": "FlashID 提供或购买的代理，由系统管理。",
        "Deleted profiles will appear here and will be automatically removed after 30 days.": "已删除的窗口将显示在此处，30 天后将自动移除。",
        "Back to All Profiles": "返回所有窗口",
        "Role:": "角色:",
        "Host (Smart Parse is supported)": "主机 (支持智能解析)",
        "Port": "端口",
        "This is an IP change link for mobile proxies.": "这是移动代理的 IP 更换链接。",
        "Manually refresh it to change the proxy's IP.": "手动刷新以更换代理的 IP。",
        "Shared proxies will update IPs across all profiles.": "共享代理将在所有窗口中更新 IP。",
        "If you don’t have this link, your proxy likely doesn’t support IP rotation.": "如果您没有此链接，您的代理可能不支持 IP 轮换。",
        "IP Address": "IP 地址",
        "Vendor": "供应商",
        "Renderer": "渲染器",
        "Audio inputs": "音频输入",
        "Audio outputs": "音频输出",
        "Video inputs": "视频输入",
        "Supported formats:": "支持的格式:",
        "host:port:username:password[change_ip_url]": "主机:端口:用户名:密码[更换IP链接]",
        "username:password@host:port[change_ip_url]": "用户名:密码@主机:端口[更换IP链接]",
        "[IPv6-host]:port:username:password[change_ip_url]": "[IPv6主机]:端口:用户名:密码[更换IP链接]",
        "username:password@[IPv6-host]:port[change_ip_url]": "用户名:密码@[IPv6主机]:端口[更换IP链接]",
        "You can also specify the proxy type in front:": "您也可以在前面指定代理类型:",
        "socks5://login:password@192.168.0.1:8000": "socks5://用户名:密码@192.168.0.1:8000",
        "https://192.168.0.1:8000:login:password": "https://192.168.0.1:8000:用户名:密码",
        "No valid proxies to check": "没有有效的代理可供检查",
        "Profile created successfully": "窗口创建成功",
        "Anyone can join using this link.": "任何人都可以使用此链接加入。",
        "Turn off": "关闭",
        "New invite link generated successfully.": "新邀请链接生成成功。",
        "Never started": "从未启动",
        "No note": "无备注",
        "Create": "创建",
        "Start": "启动",
        "Stop": "停止",
        "selected": "已选择",
        "No name": "无名称",
        "No starred profiles": "没有收藏的窗口",
        "No running profiles": "没有运行中的窗口",
        "Successfully added proxies": "成功添加代理",
        "Connection failed. Check your proxy settings and try again.": "连接失败。请检查您的代理设置并重试。",
        "The browser is running and cannot be deleted.": "浏览器正在运行,无法删除。",
        "Delete Profile": "删除窗口",
        "After deletion, it can be retrieved from the Trash Bin within 30 days.": "删除后,可在 30 天内从回收站中恢复。",
        "Restore Profiles": "恢复窗口",
        "Do you want to restore the selected profiles?": "您要恢复选中的窗口吗?",
        "If the original folder no longer exists, they will be moved to": "如果原文件夹不再存在,它们将被移至",
        "If the proxy no longer exists, it will be restored as": "如果代理不再存在,将恢复为",
        "Delete Proxy": "删除代理",
        "Are you sure you want to delete these proxies?": "您确定要删除这些代理吗?",
        "Are you sure you want to delete this proxy?": "您确定要删除此代理吗?",
        "Deleting these proxies will reset any associated profiles to": "删除这些代理将把所有关联的窗口重置为",
        ". ": "。 ",
        ".": "。",
        "Delete Profiles": "删除窗口",
        "Are you sure you want to delete the selected Profiles?": "您确定要删除选中的窗口吗?",
        "They will be moved to the Trash Bin and can be restored within 30 days.": "它们将被移至回收站,可在 30 天内恢复。",
        "Folder created successfully": "文件夹创建成功",
        "Folder updated successfully": "文件夹更新成功",
        "Folder deleted successfully": "文件夹删除成功",
        "Permanently  delete": "永久删除",
        "Launched ·": "最后启动 · ",
        "Do you want to save the updates?": "您要保存更新吗?",
        "You have made changes to this profile.": "您已对此窗口进行了更改。",
        "Confirm Save Changes": "确认保存更改",
        "Profile updated successfully": "窗口更新成功",
        "Checking proxy": "检查代理中",
        "Preparing profile": "准备窗口中",
        "Profile is ready": "窗口已就绪",
        "Applying configuration": "应用配置中",
        "Launching: Checking proxy": "启动中: 检查代理中",
        "Launching: Preparing profile": "启动中: 准备窗口中",
        "Launching: Profile is ready": "启动中: 窗口已就绪",
        "Launching: Applying configuration": "启动中: 应用配置中",
        "Launched: Profile is ready": "已启动: 窗口已就绪",
        "Disable UDP": "禁用 UDP",
        "Altered": "伪装",
        "Add FlashID Proxy for just $7": "仅需 $7 即可添加 FlashID 代理",
        "Static IP packs for secure, stable network routing.": "静态 IP 套餐，提供安全稳定的网络路由。",
        "+$7": "+$7",
        "/IP": "/IP",
        "Buy now": "立即购买",
        "Imported": "已导入",
        "0 IPs": "0 个 IP",
        "Datacenter": "数据中心",
        "Residential (ISP)": "住宅 (ISP)",
        "Buy Proxy": "购买代理",
        "No proxies yet. Click the button below to buy one.": "暂无代理。点击下方按钮购买。",
        "Import Proxies": "导入代理",
        "Socks5": "Socks5",
        "IP2Location": "IP2Location",
        "Select the proxies you want to purchase": "选择要购买的代理",
        "Location #1": "地区 #1",
        "$7/IP/mo.": "$7/IP/月",
        "Location": "地区",
        "United States": "美国",
        "IPs": "IP 数量",
        "Total": "总计",
        "Add another location": "添加另一个地区",
        "Subtotal:": "小计:",
        "Without payment system fee": "不含支付系统手续费",
        "Go to payment": "前往支付",
        "Brazil": "巴西",
        "Canada": "加拿大",
        "Chile": "智利",
        "Colombia": "哥伦比亚",
        "Germany": "德国",
        "Spain": "西班牙",
        "France": "法国",
        "United Kingdom": "英国",
        "Hong Kong": "香港",
        "Indonesia": "印度尼西亚",
        "Israel": "以色列",
        "India": "印度",
        "Italy": "意大利",
        "Japan": "日本",
        "South Korea": "韩国",
        "Mexico": "墨西哥",
        "Malaysia": "马来西亚",
        "Netherlands": "荷兰",
        "Philippines": "菲律宾",
        "Poland": "波兰",
        "Russia": "俄罗斯",
        "Singapore": "新加坡",
        "Thailand": "泰国",
        "Turkey": "土耳其",
        "Taiwan": "台湾",
        "Vietnam": "越南",
        "South Africa": "南非",
        "Australia": "澳大利亚",
    };

    function translateNode(node) {
        if (node.nodeType === 3) {
            const text = node.nodeValue.trim();
            if (text && i18n[text]) {
                node.nodeValue = node.nodeValue.replace(text, i18n[text]);
            }
        }
        else if (node.nodeType === 1) {
            if (node.tagName === 'INPUT' || node.tagName === 'TEXTAREA') {
                const ph = node.getAttribute('placeholder');
                if (ph && i18n[ph]) {
                    node.setAttribute('placeholder', i18n[ph]);
                }
            }
            node.childNodes.forEach(translateNode);
        }
    }

    const observer = new MutationObserver((mutations) => {
        mutations.forEach((mutation) => {
            mutation.addedNodes.forEach(translateNode);
            if (mutation.type === 'characterData') {
                translateNode(mutation.target);
            }
        });
    });

    translateNode(document.body);
    observer.observe(document.body, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: true
    });
});
